# -*- mode: ruby -*-
# vi: set ft=ruby :

# memo        at https://docs.vagrantup.com
# some boxes  at https://atlas.hashicorp.com/search

Vagrant.configure(2) do |config|

    config.vm.box = "chef/debian-7.7"

    # config.vm.box_check_update = false
    # config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.network "private_network", ip: "192.168.4.10"

    # Bridged networks make the machine appear as another physical device on your network.
    # config.vm.network "public_network"

    config.vm.synced_folder "../data", "/vagrant"

    config.vm.provider "virtualbox" do |vb|
        # vb.gui = true
        vb.memory = "512"
    end

    config.vm.provision :shell, path: "bootstrap.sh"

end
