# -*- mode: ruby -*-
# vi: set ft=ruby :

# docs memo     at https://docs.vagrantup.com
# some boxes    at https://atlas.hashicorp.com/search

Vagrant.configure(2) do |config|

    config.vm.box = "hashicorp/precise64"
    config.vm.hostname = "ushuaia"

    # config.vm.box_check_update = false
    # config.vm.network "forwarded_port", guest: 80, host: 8080

    config.vm.network "private_network", ip: "192.168.4.10"

    # Like another physical device on the network.
    # config.vm.network "public_network"

    config.vm.synced_folder "../data", "/vagrant"

    config.vm.provider "virtualbox" do |vb|
        # vb.gui = true
        vb.memory = "512"
    end

    config.vm.provision :shell, path: "bootstrap.sh"

    config.vm.provision "chef_solo" do |chef|
        chef.add_recipe "apt"
        chef.add_recipe "nginx::default"
    end

end
